version: '3.1'

services:
  nifi-reg:
    image: cbonami/nifi-registry:latest
    links:
      - db
    ports:
      - "18080:18080"
    environment:
      - NIFI_REGISTRY_WEB_HTTP_PORT=18080
      - NIFI_REGISTRY_FLOW_PROVIDER=git
      - NIFI_REGISTRY_GIT_REMOTE=https://github.com/cbonami/nifi-flows.git
      - NIFI_REGISTRY_GIT_USER=cbonami
      - NIFI_REGISTRY_GIT_PASSWORD=${GIT_PASSWORD}
      - NIFI_REGISTRY_DB_URL=jdbc:postgresql://db:5432/nifi_registry
      - NIFI_REGISTRY_DB_CLASS=org.postgresql.Driver
#      - NIFI_REGISTRY_DB_DIR=
      - NIFI_REGISTRY_DB_USER=nifi_registry
      - NIFI_REGISTRY_DB_PASS=${POSTGRES_PASSWORD}
      - NIFI_REGISTRY_DB_MAX_CONNS=5
      - NIFI_REGISTRY_DB_DEBUG_SQL=false
      - NIFI_REGISTRY_FLOW_STORAGE_DIR=/flow_storage
    volumes:
      - ./nifi-reg/flow_storage:/flow_storage

  # https://hub.docker.com/_/postgres/
  db:
    image: postgres:10
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=nifi_registry
    volumes:
      - ./nifi-reg/db_storage:/var/lib/postgresql/data

  adminer:
    image: adminer
    links:
      - db
    restart: always
    ports:
      - 8080:8080
