version: '3.1'

services:
  nifi-reg:
    image: cbonami/nifi-registry:latest
    links:
      - db
    ports:
      - "18080:18080"
    environment:
      - NIFI_REGISTRY_WEB_HTTP_PORT=18080

    # https://hub.docker.com/_/postgres/
  db:
    image: postgres:10
    restart: always
    environment:
      - POSTGRES_PASSWORD=very_secret
      - POSTGRES_USER=nifi_registry
    volumes:
      - ./nifi-reg/data:/var/lib/postgresql/data

  adminer:
    image: adminer
    links:
    - db
    restart: always
    ports:
    - 8080:8080
